"""empty message

Revision ID: 30437893d9c6
Revises: 
Create Date: 2018-03-18 22:53:12.108429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30437893d9c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('friends')
    op.alter_column('places', 'place_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('places', 'place_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_table('friends',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_user_id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('ratings',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
